// Deterministic, localized messages for the runtime control lane.
//
// Control-lane acknowledgements (run queued, ambiguous input, conversation
// fallback…) are intentionally NOT generated by Donna: spending an LLM turn
// to say "your request is queued" would reintroduce exactly the per-message
// cost the orchestration refactor removed. But they are user-facing, so they
// must follow the session's configured reply language. This catalog is the
// single source for those strings — never hardcode a control-lane message in
// the shell or the server directly.

const CONTROL_MESSAGES = {
  queued_for_future_run: {
    en: 'Request added to the queue — it will start automatically after the current run.',
    fr: 'Demande ajoutée à la file — elle démarrera automatiquement à la fin du run en cours.',
  },
  plan_patch_proposed: {
    en: 'Plan patch proposed. Approve it explicitly to apply it to the active plan.',
    fr: 'Modification de plan proposée. Approuvez-la explicitement pour l’appliquer au plan actif.',
  },
  ambiguous_control: {
    en: 'The runtime cannot safely classify this message.',
    fr: 'Le runtime ne peut pas classer ce message de façon sûre.',
  },
  converse_while_running: {
    en: 'Runtime run is still active. This message was treated as conversation and did not create a queued run.',
    fr: 'Un run est toujours actif. Ce message a été traité comme conversation et n’a pas créé de run en file.',
  },
  converse_while_idle: {
    en: 'Runtime is idle. This message was treated as conversation and did not create a run.',
    fr: 'Le runtime est inactif. Ce message a été traité comme conversation et n’a pas créé de run.',
  },
};

export function controlLanguage(session) {
  const raw = String(session?.language ?? 'en').toLowerCase();
  return raw.startsWith('fr') ? 'fr' : 'en';
}

export function controlMessage(session, key) {
  const entry = CONTROL_MESSAGES[key];
  if (!entry) throw new Error(`Unknown control message key: ${key}`);
  return entry[controlLanguage(session)] ?? entry.en;
}
