// Deterministic, English-only messages for the runtime control lane.
//
// Control-lane acknowledgements (run queued, ambiguous input, conversation
// fallback…) are intentionally NOT generated by Donna: spending an LLM turn
// to say "your request is queued" would reintroduce exactly the per-message
// cost the orchestration refactor removed. They are therefore English-only —
// the one language this deterministic lane can guarantee — and are never
// localized by a hardcoded fr/en catalog (a French-only fallback would still
// leave every other language unanswered). Localized, personalised replies are
// Donna's job on the conversational paths (see generateSkillAcknowledgment).
// This catalog is the single source for these strings — never hardcode a
// control-lane message in the shell or the server directly.

const CONTROL_MESSAGES = {
  queued_for_future_run: 'Request added to the queue — it will start automatically after the current run.',
  plan_patch_proposed: 'Plan patch proposed. Approve it explicitly to apply it to the active plan.',
  ambiguous_control: 'A run is already active, and this looks like a new action. Say "queue it" to run it after the current run, "modify the run" to change the active plan, "cancel" to stop the current run first — or wait for it to finish.',
  converse_while_running: 'Runtime run is still active. This message was treated as conversation and did not create a queued run.',
  converse_while_idle: 'Runtime is idle. This message was treated as conversation and did not create a run.',
};

export function controlMessage(_session, key) {
  const entry = CONTROL_MESSAGES[key];
  if (!entry) throw new Error(`Unknown control message key: ${key}`);
  return entry;
}
