import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import YAML from 'yaml';
import { managerRuntimeDir } from './env.js';

export const CACERT_CONTAINER_PATH = '/wiki-manager-ca.pem';
export const CACERT_ENV_KEYS = [
  'NODE_EXTRA_CA_CERTS',
  'SSL_CERT_FILE',
  'REQUESTS_CA_BUNDLE',
  'CURL_CA_BUNDLE',
];

export function activeCacertPath() {
  const value = process.env.WIKI_MANAGER_CACERT_PATH;
  return value ? resolve(value) : null;
}

export function cacertEnv(path = activeCacertPath(), targetPath = path) {
  if (!path) return {};
  return Object.fromEntries(CACERT_ENV_KEYS.map((key) => [key, targetPath]));
}

function parseComposeServices(composeFilePath) {
  const parsed = YAML.parse(readFileSync(composeFilePath, 'utf8')) ?? {};
  return Object.keys(parsed.services ?? {}).filter(Boolean);
}

function composeOverrideContent(cacertPath, services) {
  const serviceEntries = Object.fromEntries(
    services.map((service) => [
      service,
      {
        volumes: [`${cacertPath}:${CACERT_CONTAINER_PATH}:ro`],
        environment: cacertEnv(cacertPath, CACERT_CONTAINER_PATH),
      },
    ]),
  );
  const doc = {
    services: serviceEntries,
  };
  return [
    '# Generated by wiki-manager. Safe to delete.',
    '# Rewritten when --cacert is used with a Docker Compose command.',
    YAML.stringify(doc).trimEnd(),
    '',
  ].join('\n');
}

let _cacertOverrideCache;

export function ensureCacertComposeOverride(composeFilePath, fileName = 'cacert.compose.yml') {
  if (_cacertOverrideCache !== undefined) return _cacertOverrideCache;
  const cacertPath = activeCacertPath();
  if (!cacertPath) return (_cacertOverrideCache = null);
  if (!existsSync(cacertPath)) {
    throw new Error(`--cacert file not found: ${cacertPath}`);
  }
  const services = parseComposeServices(composeFilePath);
  if (services.length === 0) return null;
  const runtimeDir = managerRuntimeDir();
  mkdirSync(runtimeDir, { recursive: true });
  const overridePath = join(runtimeDir, fileName);
  writeFileSync(overridePath, composeOverrideContent(cacertPath, services), 'utf8');
  return (_cacertOverrideCache = overridePath);
}
