import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { maintenancePolicy,actionMode,inBuildWindow,MAINTENANCE_ACTIONS,describeError } from './policy.js';
import { createMaintenanceStore } from './store.js';
import { admitExecution,enableMaintenanceAdmission } from './admission.js';
import { createMaintenanceService } from './service.js';
const setup=()=>{const db=new DatabaseSync(':memory:');return {db,store:createMaintenanceStore(db)};};
test('policy defaults protect first ingest and every publication; build requires window',()=>{const p=maintenancePolicy({},'x');assert.equal(p.enabled,false);assert.equal(actionMode(p,'ingest','x'),'ask');assert.equal(actionMode(p,'deliver','x'),'ask');assert.equal(inBuildWindow(p),false);});
test('workspace overrides inherit and explicit target lists never authorize others',()=>{const p=maintenancePolicy({maintenanceAccess:{defaults:{enabled:true},workspaces:{x:{actions:{build:['templates/a.md']}}}}},'x');assert.equal(actionMode(p,'build','templates/a.md'),'auto');assert.equal(actionMode(p,'build','templates/b.md'),'off');assert.equal(p.actions.ingest,'ask');});
test('policy rejects invalid modes, paths, limits, mail and windows',()=>{for(const defaults of [{actions:{build:['../a']}},{limits:{buildsPerDay:-1}},{mail:{to:['invalid']}},{buildSchedule:{mode:'window',start:'99:00',end:'02:00'}}])assert.throws(()=>maintenancePolicy({maintenanceAccess:{defaults}},'x'));});
test('midnight windows use explicit timezone',()=>{const p=maintenancePolicy({maintenanceAccess:{defaults:{buildSchedule:{mode:'window',start:'22:00',end:'03:00',timezone:'UTC'}}}},'x');assert.equal(inBuildWindow(p,new Date('2026-10-05T23:00Z')),true);assert.equal(inBuildWindow(p,new Date('2026-10-05T12:00Z')),false);});
test('reservations count in-flight admissions and unknown previous-day effects',()=>{const {db,store}=setup();try{store.reserve({id:'a',workspace:'x',policy:'v',kind:'actions',cycle:'c',limit:1,period:'yesterday'});assert.throws(()=>store.reserve({id:'b',workspace:'x',policy:'v',kind:'actions',cycle:'d',limit:1}),/budget/);store.settle('a');store.settle('a');assert.equal(store.reservations('x')[0].status,'consumed');store.reserve({id:'b',workspace:'x',policy:'v',kind:'actions',cycle:'d',limit:1});}finally{db.close();}});
test('a certain pre-dispatch refusal releases capacity; retry reserves it again',()=>{const {db,store}=setup();try{const r={id:'a',workspace:'x',policy:'v',kind:'actions',cycle:'c',limit:1};store.reserve(r);store.settle('a',{started:false});assert.equal(store.reserve({...r,cycle:'d'}).status,'reserved');assert.throws(()=>store.reserve({...r,id:'b'}),/budget/);}finally{db.close();}});
test('new content replaces the old decision; stale approval and cross-workspace decisions fail',()=>{const {db,store}=setup();try{const a=store.propose('x',{action:'ingest',target:'raw',version:'1',summary:'first'});const b=store.propose('x',{action:'ingest',target:'raw',version:'2',summary:'second'});assert.throws(()=>store.decide('x',a.id,a.version,true),/replaced/);assert.throws(()=>store.decide('y',b.id,b.version,true));store.decide('x',b.id,b.version,false);assert.equal(store.propose('x',b.candidate).status,'refused');assert.equal(store.requests('x').filter(r=>r.status==='pending').length,0);}finally{db.close();}});
test('foreground pending before background admission wins the resource',async()=>{const w='priority';enableMaintenanceAdmission(w);const held=await admitExecution(w,{locks:['*']},{background:true});const order=[];const fore=admitExecution(w,{locks:['*']}).then(release=>{order.push('foreground');release();});const back=admitExecution(w,{locks:['*']},{background:true}).then(release=>{order.push('background');release();});held();await Promise.all([fore,back]);assert.deepEqual(order,['foreground','background']);});
test('aborted waiter does not steal or leak admission',async()=>{enableMaintenanceAdmission('abort');const held=await admitExecution('abort',{},{background:true});const c=new AbortController();const pending=admitExecution('abort',{},{background:true,signal:c.signal});c.abort();await assert.rejects(pending);held();(await admitExecution('abort',{},{background:true}))();});
test('disabled maintenance does not call tools or a model; scoped authority cannot approve',async()=>{const {db}=setup();let calls=0;const service=createMaintenanceService({db,getContext:async()=>{calls++;},readDocument:()=>({}),baseUrl:'http://localhost'});await service.tick('x');assert.equal(calls,0);assert.equal(service.authorizeBridge('unknown','token'),null);assert.equal(service.status('x').enabled,false);await service.close();db.close();});

function harness({facts:override={},runtime=null,gate=null}={}){
  const {db}=setup();let version='a';let executions=[];let access={maintenanceAccess:{defaults:{enabled:true,limits:{sourceQuietMinutes:0}}}};
  const facts=()=>({wikiHash:'wiki',pending:[{path:'raw/untracked/a.md',hash:version,stable:true,protected:false}],index:{enabled:false,fresh:true},deliverables:[],publications:[],proposals:[],...override});
  const provider={serverName:'production',health:'available',capability:{supportedOperations:['ingest','doctor','index','ingest_rebuild','build','export','polish','send'],inputSchema:{type:'object',additionalProperties:true}}};
  const session={workspace:'x',workspacePath:'/private/tmp/nonexistent-maintenance-test',mcp:{wiki:{tools:[{name:'wiki_maintenance_state'}]}},capabilityRegistry:{providersFor:(capability)=>capability==='agent.maintain'?(runtime?[{runtimeProvider:runtime,runtimeId:'gw',health:'available',capability:{supportedOperations:['run']}}]:[]):[provider]}};
  const service=createMaintenanceService({db,baseUrl:'http://localhost',getContext:async()=>({session}),readDocument:()=>access,callTool:async(_mcp,_server,tool,args)=>{if(tool==='wiki_maintenance_state')return facts();if(tool==='agent_execute'){executions.push(args);return {accepted:true,jobId:'job-'+executions.length};}if(tool==='agent_status'){if(gate)await gate;return {status:'done',result:{}};}throw new Error(tool);}});
  return {db,service,executions,change:(v)=>{version=v;},policy:(p)=>{access=p;}};
}
test('pending ingestion does not prevent an independent diagnostic; approval is exact and dispatch reserves',async()=>{const h=harness();try{const pending=await h.service.runCandidate('x','cycle',{action:'ingest',target:'raw/untracked'});assert.equal(pending.status,'pending');assert.equal(h.executions.length,0);const doctor=await h.service.runCandidate('x','cycle',{action:'doctor',target:'workspace'});assert.equal(doctor.status,'done');await h.service.decide('x',pending.request.id,pending.request.version,true);const result=await h.service.runCandidate('x','cycle2',{action:'ingest',target:'raw/untracked'});assert.equal(result.status,'done');assert.equal(h.executions.length,2);assert.deepEqual(h.executions[1].arguments.maintenanceSelection,[{path:'raw/untracked/a.md',hash:'a'}]);assert.ok(h.service.store.reservations('x').every(r=>r.status==='consumed'));}finally{await h.service.close();h.db.close();}});
test('stale approval is rejected at decision time and replaced by current content',async()=>{const h=harness();try{const pending=await h.service.runCandidate('x','cycle',{action:'ingest',target:'raw/untracked'});h.change('b');await assert.rejects(h.service.decide('x',pending.request.id,pending.request.version,true),/replaced/);assert.equal(h.service.status('x').requests.filter(r=>r.status==='pending').length,1);assert.equal(h.executions.length,0);}finally{await h.service.close();h.db.close();}});
test('source refusal suppresses unchanged bytes but allows changed content',async()=>{const h=harness();try{const pending=await h.service.runCandidate('x','cycle',{action:'ingest',target:'raw/untracked'});await h.service.decide('x',pending.request.id,pending.request.version,false);assert.ok(!(await h.service.state('x')).candidates.some(c=>c.action==='ingest'));h.change('b');assert.ok((await h.service.state('x')).candidates.some(c=>c.action==='ingest'));}finally{await h.service.close();h.db.close();}});
test('revoking policy prevents a previously approved action',async()=>{const h=harness();try{const pending=await h.service.runCandidate('x','cycle',{action:'ingest',target:'raw/untracked'});await h.service.decide('x',pending.request.id,pending.request.version,true);h.policy({maintenanceAccess:{defaults:{enabled:false}}});await assert.rejects(h.service.runCandidate('x','cycle2',{action:'ingest',target:'raw/untracked'}),/disabled/);assert.equal(h.executions.length,0);}finally{await h.service.close();h.db.close();}});

test('routine sync/doctor run without a model; no gateway cycle when nothing else is due',async()=>{let launches=0;const runtime={execute:async()=>{launches++;return {runId:'r'};},status:async()=>({status:'completed'}),cancel:async()=>{}};const h=harness({facts:{pending:[],proposals:['p.json']},runtime});try{await h.service.tick('x');assert.deepEqual(h.executions.map(e=>e.operation),['doctor']);assert.equal(launches,0);}finally{await h.service.close();h.db.close();}});
test('the agent view never contains routine work',async()=>{const h=harness({facts:{pending:[],proposals:['p.json']}});try{assert.ok((await h.service.state('x')).candidates.some(c=>c.action==='doctor'));assert.ok(!(await h.service.state('x',{forAgent:true})).candidates.some(c=>c.action==='doctor'));}finally{await h.service.close();h.db.close();}});
test('maintenance only updates an export that already exists, never a first one',async()=>{const d={template:'templates/a.md',output:'deliverables/a.md',version:'v',fresh:true,reasons:[]};const none=harness({facts:{pending:[],deliverables:[{...d,artifacts:{export:false,polish:false}}]}});const some=harness({facts:{pending:[],deliverables:[{...d,artifacts:{export:true,polish:false}}]}});try{assert.ok(!(await none.service.state('x')).candidates.some(c=>c.action==='deliver'));const c=(await some.service.state('x')).candidates.find(c=>c.action==='deliver');assert.equal(c.operation,'export');assert.match(c.summary,/existing export/);}finally{for(const h of [none,some]){await h.service.close();h.db.close();}}});
test('a stale deliverable is explained in words, not reason codes',async()=>{const h=harness({facts:{pending:[],deliverables:[{template:'templates/a.md',output:'deliverables/a.md',version:'v',fresh:false,reasons:['knowledge_changed','output_modified'],artifacts:{}}]}});try{const c=(await h.service.state('x')).candidates.find(c=>c.action==='build');assert.match(c.summary,/the wiki content changed/);assert.doesNotMatch(c.summary,/knowledge_changed/);assert.match(describeError('maintenance_budget_exhausted'),/budget/);}finally{await h.service.close();h.db.close();}});
test('a runtime shutdown neither pauses maintenance nor cancels jobs',async()=>{const h=harness();await h.service.close();try{assert.equal(h.service.status('x').paused,false);}finally{h.db.close();}});
test('reads, worktree curation and mail never hold a user task',()=>{for(const a of ['doctor','curate','mail'])assert.equal(MAINTENANCE_ACTIONS[a].scopes,null);assert.deepEqual(MAINTENANCE_ACTIONS.sync.scopes('x'),['raw/untracked']);});
test('a foreground task waiting behind maintenance is announced with the holder',async()=>{const w='announce';enableMaintenanceAdmission(w);const held=await admitExecution(w,{locks:['workspace-write']},{background:true,label:'maintenance: Ingest 2 new source(s)'});const heard=[];const fore=admitExecution(w,{locks:['deliverable:a']},{onWait:(names)=>heard.push(names)});await new Promise(r=>setTimeout(r,150));held();(await fore)();assert.deepEqual(heard,['maintenance: Ingest 2 new source(s)']);});
test('a hand-edited deliverable is never rebuilt without a decision, even with build: auto',async()=>{const h=harness({facts:{pending:[],deliverables:[{template:'templates/a.md',output:'deliverables/a.md',version:'v',fresh:false,reasons:['output_modified'],artifacts:{}}]}});try{h.policy({maintenanceAccess:{defaults:{enabled:true,actions:{build:'auto'},buildSchedule:{mode:'window',start:'00:00',end:'23:59',timezone:'UTC'},limits:{sourceQuietMinutes:0}}}});const c=(await h.service.state('x')).candidates.find(c=>c.action==='build');assert.equal(c.mode,'ask');const r=await h.service.runCandidate('x','cycle',{action:'build',target:'templates/a.md'});assert.equal(r.status,'pending');assert.equal(h.executions.length,0);}finally{await h.service.close();h.db.close();}});
test('mail is routine: one alert per new failure batch, recipients only from the policy',async()=>{const h=harness({facts:{pending:[],proposals:['p.json']}});try{h.policy({maintenanceAccess:{defaults:{enabled:true,mail:{to:['ops@example.org'],on:['failure']},limits:{sourceQuietMinutes:0}}}});h.service.store.event('x',{kind:'failure',message:'Maintenance: Failed: export'});const mails=(await h.service.state('x')).candidates.filter(c=>c.action==='mail');assert.equal(mails.length,1);assert.equal(mails[0].target,'ops@example.org');assert.ok(!(await h.service.state('x',{forAgent:true})).candidates.some(c=>c.action==='mail'));await h.service.tick('x');assert.ok(h.executions.some(e=>e.operation==='send'&&e.arguments.to==='ops@example.org'));assert.ok(!(await h.service.state('x')).candidates.some(c=>c.action==='mail'),'the same alert is not sent twice');}finally{await h.service.close();h.db.close();}});
test('an executing maintenance action counts as an active run',async()=>{let release;const gate=new Promise(r=>{release=r;});const h=harness({facts:{pending:[],proposals:['p.json']},gate});try{assert.equal(h.service.isActive('x'),false);const running=h.service.runCandidate('x','cycle',{action:'doctor',target:'workspace'});for(let i=0;i<50&&!h.service.isActive('x');i++)await new Promise(r=>setTimeout(r,10));assert.equal(h.service.isActive('x'),true);assert.deepEqual(h.service.activeRuns().map(r=>r.kind),['maintenance']);release();await running;assert.equal(h.service.isActive('x'),false);}finally{await h.service.close();h.db.close();}});
